spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeit
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: lt.kanaporis.outbox
      auto-offset-reset: earliest
    listener:
      ack-mode: MANUAL_IMMEDIATE
